sync_slam_toolbox_node:
  ros__parameters:
    slam_toolbox:
      use_sim_time: false     # Set to true if using simulated time
      mode: mapping           # SLAM mode (mapping or localization)
      odom_frame: "odom"      # Frame for odometry data
      base_frame: "base_link" # Frame for the base of the robot
      map_frame: "map"        # Frame for the map
      scan_topic: "/my_robot/laser_scan/center"  # LaserScan topic
      scan_downsample_factor: 1   # Factor to downsample laser scans
      transform_tolerance: 0.2   # Tolerance for transform cache in seconds
      map_resolution: 0.05        # Resolution of the occupancy grid map
      map_size: 20.0              # Size of the map in meters
      map_publish_period: 2.0     # Period to publish the map in seconds
      use_odom: false


